function [ userInterface ] = uiOut( y, height,title,tip )
font = 10;

userInterface = uicontrol('Style', 'Text', 'String',...
            title,...
            'ForegroundColor', [1 1 1], 'FontSize', 10,...
            'BackgroundColor', [0 0 0],...
            'Position', [10, y, 220, height],'tooltip',...
            tip);


end

